CREATE TABLE IF NOT EXISTS "Tank_Simulator" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Level" double precision DEFAULT 0,
  "Outlet_Valve(%)" double precision DEFAULT 0,
  "Pump_Speed(%)" double precision DEFAULT 0,
  "Pump_running" boolean DEFAULT false,
  "Alarm" boolean DEFAULT false,
  "OutletValve_SP" double precision DEFAULT 0,
  "TankLevel_SP" double precision DEFAULT 0,
  "RemoteStart" boolean DEFAULT false,
  source text DEFAULT '',
  updated_at timestamptz DEFAULT now()
);

INSERT INTO "Tank_Simulator" (id) 
SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM "Tank_Simulator" WHERE id = 1);